{% set setup_py = load_setup_py_data() %}
package:
    name: 'tardis'
    version: {{ setup_py.get('version') }}

source:
    git_url: https://github.com/tardis-sn/tardis.git
    git_tag: master

build:
    script: python setup.py build install

requirements:
    run:
        - python=3
        - numpy=1.15
        - scipy=1.1
        - pandas=0.24
        - astropy=3
        - numexpr
        - Cython=0.29
        - networkx
        - pyyaml
        - jsonschema
        #- pyne=0.5
        - pytables
        - h5py
        - jupyter
        - notebook
        - matplotlib
        - graphviz
        - pygraphviz
        #- sphinx
        #- nbconvert
        #- numpydoc
        #- docutils
        #- nbformat
        #- nbsphinx
        #- sphinx_bootstrap_theme
        #- sphinxcontrib-bibtex
        #- sphinx_rtd_theme
        #- git-lfs
        #- pytest
        #- pytest-html
        #- requests
        #- coverage
        #- docopt
        #- pytest-cov
        #- codecov

    build:
        - python
        - setuptools
        - numpy
        - astropy
        - Cython

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE.rst
    summary: {{ setup_py.get('description') }}
