name: update-authors

on:
  pull_request:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: tardis-sn/tardis_zenodo
          token: 153d8ce162e6e621c952e06b6a0cc9632c6b71ee
          path: tardis_zenodo

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v1 
        with:
            channels: conda-forge, defaults
            mamba-version: "*"

      - name: Install packages
        shell: bash -l {0}
        run: mamba install jupyter nbconvert numpy pandas orcid -y
