parameters:
  - name: "fetchRefdata"
    type: boolean
    default: false

  - name: "useMamba"
    type: boolean
    default: false

  - name: "skipInstall"
    type: boolean
    default: false

steps:
  - checkout: self
    displayName: "Fetch TARDIS repository"

  - ${{ eq(parameters.fetchRefdata, true) }}:
    - checkout: git://TARDIS/tardis-refdata
      lfs: true
      displayName: "Fetch TARDIS reference data"

  - bash: echo "##vso[task.setvariable variable=shellopts]errexit"
    displayName: "Force exit on error (bash)"
    condition: eq(variables['Agent.OS'], 'Linux')

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: "Add conda to PATH"

  - bash: sudo chown -R $USER $CONDA
    displayName: "Take ownership of conda installation (macOS)"
    condition: eq(variables['Agent.OS'], 'Darwin')

  - ${{ eq(parameters.useMamba, true) }}:
    - bash: conda install mamba -c conda-forge -y
      displayName: "Install Mamba package manager"

  - ${{ eq(parameters.skipInstall, false) }}:
    - bash: |
        cd $REPO_DIR/tardis
        $PACKAGE_MANAGER env create -f tardis_env3.yml
      displayName: "Install TARDIS environment"

  - ${{ eq(parameters.skipInstall, false) }}:
    - bash: |
        cd $REPO_DIR/tardis
        source activate tardis
        python setup.py build_ext --inplace
      displayName: "TARDIS build & install"
