# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#pr: none
schedules:
  - cron: "30 22 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true

variables:
  system.debug: "true"
  tardis.build.dir: $(Build.Repository.LocalPath)

pool:
  vmImage: "ubuntu-latest"

jobs:
- job: zenodo_json
  steps:

    - task: DownloadSecureFile@1
      name: zenodoSecretKey
      displayName: 'Download Zenodo secret key'
      inputs:
        secureFile: 'key_secret.json'

    - task: DownloadSecureFile@1
      name: authorOrder
      displayName: 'Download author order file'
      inputs:
        secureFile: 'author_order.txt'

    - task: DownloadSecureFile@1
      name: nonCommitContributors
      displayName: 'Download non commit contributors file'
      inputs:
        secureFile: 'non_commit_contributors.txt'

    - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
        sudo chown -R $USER $CONDA
      displayName: "Add CONDA to path"

    - bash: |
        sh ci-helpers/install_tardis_env.sh
      displayName: "Install TARDIS env"
    
    - bash: |
        source activate tardis
        conda install -c conda-forge orcid --yes --no-update-deps
      displayName: "Install ORCID package "

    - bash: |
        source activate tardis
        git clone git@github.com:tardis-sn/tardis_zenodo.git
      displayName: "Clone tardis_zenodo repo"

    - bash: |
        source activate tardis
        cd tardis_zenodo
        cp $(zenodoSecretKey.secureFilePath) .
        cp $(authorOrder.secureFilePath) .
        cp $(nonCommitContributors.secureFilePath) .
        jupyter nbconvert gather_data.ipynb --execute --ExecutePreprocessor.timeout=6000
        cat .zenodo.json
      displayName: "Running gather_data notebook"

#- job: gh_release
#  dependsOn: zenodo_json
#  steps:
#    - bash: |
#        echo "##vso[task.prependpath]$CONDA/bin"
#        sudo chown -R $USER $CONDA
#      displayName: "Add CONDA to path"
#  
#    - bash: |
#        sh ci-helpers/install_tardis_env.sh
#      displayName: "Install TARDIS env"
#  
#    - bash: |
#        source activate tardis
#        python setup.py install
#      displayName: "Build & install TARDIS"
#  
#    - bash: |
#        source activate tardis
#        echo "##vso[task.setvariable variable=version]$(python -c 'import tardis; print(tardis.__version__)')"
#      displayName: "Get TARDIS version number"
#  
#    - bash: |
#        echo $(VERSION)
#      displayName: "Recover TARDIS version number"
#  
#    - task: GitHubRelease@1
#      inputs:
#        gitHubConnection: "wkerzendorf"
#        repositoryName: "$(Build.Repository.Name)"
#        action: "create"
#        target: "$(Build.SourceVersion)"
#        tagSource: "userSpecifiedTag"
#        tag: "$(VERSION)"
#        title: "TARDIS v$(VERSION)"
#        isPreRelease: true
#        changeLogCompareToRelease: "lastFullRelease"
#        changeLogType: "commitBased"