# For more information on how to use this pipeline please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

trigger:
  - master

variables:
  package.manager: "mamba"
  workspace.dir: "$(Pipeline.Workspace)/s"
  codecov.token: "a876d307-9ed5-4f5d-a6c4-e58291ac4111"
  system.debug: "false"

jobs:
  - job: "Test"
    pool:
      vmImage: $[variables.vm_Image]

    strategy:
      matrix:
        linux:
          vm_Image: "ubuntu-latest"
        mac:
          vm_Image: "macOS-latest"
      maxParallel: 2

    steps:
      - checkout: self

      - checkout: git://TARDIS/tardis-refdata
        lfs: true

      - bash: echo "##vso[task.setvariable variable=shellopts]errexit"
        displayName: "Force exit on error (bash) "
        condition: eq(variables['Agent.OS'], 'Linux')

      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: "Add conda to PATH"

      - bash: sudo chown -R $USER $CONDA
        displayName: "Take ownership of conda installation (macOS)"
        condition: eq(variables['Agent.OS'], 'Darwin')

      - bash: conda install mamba -c conda-forge -y
        displayName: "Install Mamba package manager"
        condition: eq(variables['package.manager'], 'mamba')

      - bash: |
          cd $WORKSPACE_DIR/tardis
          $PACKAGE_MANAGER env create -f tardis_env3.yml
        displayName: "Install TARDIS environment"

      - bash: |
          cd $WORKSPACE_DIR/tardis
          source activate tardis
          python setup.py build_ext --inplace
        displayName: "TARDIS build"

      - bash: |
          cd $WORKSPACE_DIR/tardis
          source activate tardis
          pip install pytest-azurepipelines
          pytest tardis --tardis-refdata=$WORKSPACE_DIR/tardis-refdata --cov=tardis --cov-report=xml --cov-report=html
        displayName: "TARDIS test"

      - bash: bash <(curl -s https://codecov.io/bash)
        displayName: "Upload to codecov.io"
