# For more information on how to use this pipeline please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

trigger:
  - master

variables:
  working.dir: '$(Agent.BuildDirectory)/s'
  codecov.token: 'a876d307-9ed5-4f5d-a6c4-e58291ac4111'
  system.debug: false

jobs:
  - job: 'Test'
    pool:
      vmImage: $[variables.vm_Image]

    strategy:
      matrix:
        linux:
          vm_Image: 'ubuntu-latest'

        mac:
          vm_Image: 'macOS-latest'

      maxParallel: 2

    steps:
      - template: templates/default.yml
        parameters:
          workingDir: '$(working.dir)'
          packageManager: 'mamba'
          fetchRefdata: true

      - bash: |
          cd $(working.dir)/tardis
          source activate tardis
          pip install pytest-azurepipelines
          pytest tardis --tardis-refdata=$(working.dir)/tardis-refdata --cov=tardis --cov-report=xml --cov-report=html
        displayName: 'TARDIS test'

      - bash: bash <(curl -s https://codecov.io/bash)
        displayName: 'Upload to codecov.io'
