# For more information on how to use this template please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

trigger: none
pr: [ master ]

schedules:
  - cron: '30 22 * * 5'
    displayName: Scheduled update
    branches:
      include:
        - master
    always: false

variables:
  system.debug: false
  tardis.zenodo.dir: '$(Build.SourcesDirectory)/tardis_zenodo'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: update_json
    steps:
      - template: templates/default.yml
        parameters:
          useMamba: true
          skipInstall: true
          installSSHKey: true

      - task: DownloadSecureFile@1
        name: zenodoSecretKey
        displayName: 'Recover secret file'
        inputs:
          secureFile: 'key_secret.json'

      - task: DownloadSecureFile@1
        name: authorOrder
        displayName: 'Recover secret file'
        inputs:
          secureFile: 'author_order.txt'

      - task: DownloadSecureFile@1
        name: nonCommitContributors
        displayName: 'Recover secret file'
        inputs:
          secureFile: 'non_commit_contributors.txt'

      - bash: $(package.manager) create -n zenodo python=3.6 jupyter nbconvert numpy pandas orcid -c conda-forge -y
        displayName: 'Create CONDA environment'

      - bash: |
          git clone https://$GH_TOKEN@github.com/tardis-sn/tardis_zenodo.git $(tardis.zenodo.dir)
        env:
          GH_TOKEN: $(epassaro_pat)
        displayName: 'Clone tardis_zenodo repository'

      - bash: |
          cp $(zenodoSecretKey.secureFilePath) $(tardis.zenodo.dir)
          cp $(authorOrder.secureFilePath) $(tardis.zenodo.dir)
          cp $(nonCommitContributors.secureFilePath) $(tardis.zenodo.dir)
        displayName: 'Copy secret files'

      - bash: |
          source activate zenodo
          cd $(tardis.zenodo.dir)
          jupyter nbconvert gather_data.ipynb --to html --execute --ExecutePreprocessor.timeout=6000
        displayName: 'Render notebook'

      - bash: |
          source activate zenodo
          cd $(tardis.zenodo.dir)
          jupyter nbconvert gather_data.ipynb --to html --allow-errors --execute --ExecutePreprocessor.timeout=6000
        displayName: 'Render notebook (allow errors)'
        condition: failed()

      - bash: |
          cd $(Build.SourcesDirectory)
          git clone git@github.com:tardis-sn/tardis.git out
          cd out

          git config --local user.name "TARDIS bot"
          git config --local user.email "wkerzendorf+tardis@gmail.com"

          cp $(tardis.zenodo.dir)/.zenodo.json .zenodo.json
          git add .zenodo.json

          if git diff --staged --quiet; then
             echo "No changes made"
             exit 0
          else
            git commit -m "Update author list [skip ci]"
            git push origin master
          fi
        displayName: 'Push changes'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(tardis.zenodo.dir)/gather_data.html'
          artifact: 'report'
          publishLocation: 'pipeline'
        condition: succeededOrFailed()
